out_dir_inference: outputs/inference
dataset_name: dl3dv


# Only render a stride of the cameras from the 3DGS
target_index_subsample: 1

# Do evaluation
do_eval: false

# Don't read and write the depth
use_depth: true


# Video output fps
out_fps: 15

# Assume static scenes in default
target_index_manual: null
target_index_manual_start_idx: null

## Export file config
# Output a grid of results, if yes, how many scenes to visualize in one grid
save_grid: false
num_grid_samples: 4
# Output RGB decoder output next to the 3DGS rendering
save_gt_input: true
# Output a separate file of the RGB decoder output
save_video_input: true
# Output annotated gt depth
save_gt_depth: true
# Save a RGB-decoded version of the latents
save_rgb_decoding: false
# Output 3D gaussians as simple ply file
save_gaussians: true
# Output 3D gaussians using the original 3DGS export script
save_gaussians_orig: true
# Skip existing generated file
skip_existing: false
