out_dir_inference: outputs/demo/lyra_custom

# Define dataset name defined in src/models/data/registry.py
dataset_name: dl3dv # Use pre-generated latents
# dataset_name: lyra_dynamic_demo_generated # Generate own latents

# Order of camera trajectory indices
static_view_indices_fixed: ['5', '0', '1', '2', '3', '4']

# Only render each 4. frame
target_index_subsample: 4

# Inherit from these configs the model part etc.
config_path: [configs/training/default.yaml, configs/training/3dgs_res_704_1280_views_121_multi_6_dynamic_prune.yaml]

# For dynamic scenes, set target time
set_manual_time_idx: true

# Only create outputs for specified target times (between 0=min and 120=max)
target_index_manual: [0, 60, 120]

# Alternative: Loop over start and number of time indices with given stride
# target_index_manual: null
# target_index_manual_stride: 1
# target_index_manual_start_idx: 0
# target_index_manual_num_idx: 121

# Update path to where the static Lyra checkpoint is downloaded
ckpt_path: checkpoints/Lyra/lyra_dynamic.pt
